language: python
os:
  - linux
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python your-daemon-or-script.py
#   - curl https://www.alpacapapa.com/codelist
#   - curl https://www.alpacapapa.com/pushimage
jobs:
  include:
    - stage: test
      script: python test_1.py
    - # stage name not required, will continue to use `test`
      script: python test_2.py
    - stage: deploy
      script: python your-daemon-or-script.py