FORMAT: 1A
HOST: https://www.goldenshark.xyz/

# GoldenShark

Thz Spider API.

## Thz Details [/thzdetails]

### List All Thz Details [GET]

+ Response 200 (application/json)

        [
            {
                "_type": "dict",
                "code": "",
                "href": "",
                "imgf": "",
                "name": "",
                "text": ""
            }
        ]