FORMAT: 1A
HOST: http://www.goldenshark.cf/

# GoldenShark

Thz Spider API.

## Thz Details [/thzdetails]

### List All Thz Details [GET]

+ Response 200 (application/json)

        [
            {
                "_type": "dict",
                "code": "HNDS-055",
                "href": "http://vipthz.com/thread-1785014-1-1.html",
                "imgf": "http://pic.thzhd.wang/forum/201803/13/183818qgjzlejtvgjot20g.jpg",
                "name": "椎名そら",
                "text": "[hnds-055]全員に告白されたから子作り"
            }
        ]

### Test POST [POST]

+ Request (application/json)

        null

+ Response 201 (application/json)

        Test. POSTPOSTPOST...